apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
    spec:
      containers:
      - name: api-gateway
        image: ghcr.io/company/api-gateway:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          value: "3000"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service.sap-microservices.svc.cluster.local:3001"
        - name: USER_SERVICE_URL
          value: "http://user-service.sap-microservices.svc.cluster.local:3002"
        - name: CONTENT_SERVICE_URL
          value: "http://content-service.sap-microservices.svc.cluster.local:3005"
        - name: SUBSCRIPTION_SERVICE_URL
          value: "http://subscription-service.sap-microservices.svc.cluster.local:3003"
        - name: REDIS_URL
          value: "redis://redis-manager:6379"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    component: gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: api-gateway
