apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: sap-microservices
  labels:
    app: content-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
        version: v1
    spec:
      containers:
      - name: content-service
        image: gcr.io/sap-project-466005/content-service:latest
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: "3005"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: mongodb-content-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: redis-url
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: sap-microservices
spec:
  selector:
    app: content-service
  ports:
  - port: 3005
    targetPort: 3005
    name: http
  type: ClusterIP
