# 🔐 SAP Backend Microservices - Secrets Configuration
# MongoDB + Supabase + Redis secrets for production deployment

apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # MongoDB Connection Strings (Update these with your actual MongoDB Atlas credentials)
  mongodb-auth-url: "mongodb+srv://YOUR_MONGODB_USERNAME:YOUR_MONGODB_PASSWORD@YOUR_CLUSTER.mongodb.net/sap_auth?retryWrites=true&w=majority"
  mongodb-users-url: "mongodb+srv://YOUR_MONGODB_USERNAME:YOUR_MONGODB_PASSWORD@YOUR_CLUSTER.mongodb.net/sap_users?retryWrites=true&w=majority"
  mongodb-content-url: "mongodb+srv://YOUR_MONGODB_USERNAME:YOUR_MONGODB_PASSWORD@YOUR_CLUSTER.mongodb.net/sap_content?retryWrites=true&w=majority"
  mongodb-subscription-url: "mongodb+srv://YOUR_MONGODB_USERNAME:YOUR_MONGODB_PASSWORD@YOUR_CLUSTER.mongodb.net/sap_subscriptions?retryWrites=true&w=majority"
  
  # Redis Connection String (Update with your Redis instance)
  redis-url: "redis://YOUR_REDIS_HOST:6379"

---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # Supabase Configuration (Replace with your actual Supabase project credentials)
  supabase-url: "https://leaekgpafpvrvykeuvgk.supabase.co"
  supabase-anon-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlYWVrZ3BhZnB2cnZ5a2V1dmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDE2NzQ3ODMsImV4cCI6MjAxNzI1MDc4M30.z_4PkJu8Z7ZfJHmbjpnz2mJJ4tNFTUK5fYWWXR6Qwvs"
  supabase-service-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlYWVrZ3BhZnB2cnZ5a2V1dmdrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwMTY3NDc4MywiZXhwIjoyMDE3MjUwNzgzfQ.r8X1L4bJvJfB3BqVYfYm6VJeEv8nT5KYVCOhW4RyQ-g"

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # JWT Secret for authentication service (Generate secure 32+ character secrets)
  jwt-secret: "GENERATE_32_CHAR_SECRET_HERE_FOR_PRODUCTION_USE"
  jwt-refresh-secret: "GENERATE_DIFFERENT_32_CHAR_REFRESH_SECRET_HERE"

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # Payment Gateway Keys (Stripe/Razorpay/etc)
  gateway-key: "your-payment-gateway-secret-key"
  webhook-secret: "your-payment-webhook-secret"

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: sap-microservices
data:
  # Service URLs for internal communication
  AUTH_SERVICE_URL: "http://auth-service.sap-microservices.svc.cluster.local:3001"
  USER_SERVICE_URL: "http://user-service.sap-microservices.svc.cluster.local:3002"
  CONTENT_SERVICE_URL: "http://content-service.sap-microservices.svc.cluster.local:3005"
  SUBSCRIPTION_SERVICE_URL: "http://subscription-service.sap-microservices.svc.cluster.local:3003"
  
  # Environment settings
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  
  # Feature flags
  ENABLE_ANALYTICS: "true"
  ENABLE_CACHING: "true"
  ENABLE_RATE_LIMITING: "true"
