# 🔐 SAP Backend Microservices - Secrets Configuration
# MongoDB + Supabase + Redis secrets for production deployment

apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # MongoDB Connection Strings (Update with your actual MongoDB cluster)
  mongodb-auth-url: "mongodb+srv://username:password@cluster.mongodb.net/auth_db?retryWrites=true&w=majority"
  mongodb-users-url: "mongodb+srv://username:password@cluster.mongodb.net/users_db?retryWrites=true&w=majority"
  mongodb-content-url: "mongodb+srv://username:password@cluster.mongodb.net/content_db?retryWrites=true&w=majority"
  
  # Redis Connection String (GCP Memorystore)
  redis-url: "redis://redis-cluster.c1.asia-south1-1.gce.cloud.redislabs.com:12345"

---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # Supabase Configuration (Update with your actual Supabase project)
  supabase-url: "https://your-project-id.supabase.co"
  supabase-anon-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdXItcHJvamVjdC1pZCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjM5MzE3OTUwLCJleHAiOjE5NTQ4OTM5NTB9.example"
  supabase-service-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdXItcHJvamVjdC1pZCIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2MzkzMTc5NTAsImV4cCI6MTk1NDg5Mzk1MH0.example"

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # JWT Secret for authentication service
  jwt-secret: "your-super-secure-jwt-secret-key-here-change-this-in-production"
  jwt-refresh-secret: "your-super-secure-jwt-refresh-secret-key-here"

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # Payment Gateway Keys (Stripe/Razorpay/etc)
  gateway-key: "your-payment-gateway-secret-key"
  webhook-secret: "your-payment-webhook-secret"

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: sap-microservices
data:
  # Service URLs for internal communication
  AUTH_SERVICE_URL: "http://auth-service.sap-microservices.svc.cluster.local:3001"
  USER_SERVICE_URL: "http://user-service.sap-microservices.svc.cluster.local:3002"
  CONTENT_SERVICE_URL: "http://content-service.sap-microservices.svc.cluster.local:3005"
  SUBSCRIPTION_SERVICE_URL: "http://subscription-service.sap-microservices.svc.cluster.local:3003"
  
  # Environment settings
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  
  # Feature flags
  ENABLE_ANALYTICS: "true"
  ENABLE_CACHING: "true"
  ENABLE_RATE_LIMITING: "true"
