# 🔐 SAP Backend Microservices - Secrets Configuration
# MongoDB + Supabase + Redis secrets for production deployment

apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # MongoDB Connection Strings - REPLACE WITH YOUR ACTUAL ATLAS CREDENTIALS
  mongodb-auth-url: "mongodb+srv://theja4386:SaiTeja%40123@sap-backend-cluster.zlzcxpz.mongodb.net/auth_db?retryWrites=true&w=majority"
  mongodb-users-url: "mongodb+srv://theja4386:SaiTeja%40123@sap-backend-cluster.zlzcxpz.mongodb.net/users_db?retryWrites=true&w=majority"
  mongodb-content-url: "mongodb+srv://theja4386:SaiTeja%40123@sap-backend-cluster.zlzcxpz.mongodb.net/content_db?retryWrites=true&w=majority&appName=Sap-Backend-Cluster"
  
  # Redis Connection String (Internal cluster Redis)
  redis-url: "redis://redis-service.sap-microservices.svc.cluster.local:6379"
  
  # Elasticsearch Connection String (Internal cluster Elasticsearch)
  elasticsearch-url: "http://elasticsearch-service.sap-microservices.svc.cluster.local:9200"

---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # Supabase Configuration (Replace with your actual Supabase project credentials)
  supabase-url: "https://leaekgpafpvrvykeuvgk.supabase.co"
  supabase-anon-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlYWVrZ3BhZnB2cnZ5a2V1dmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDE2NzQ3ODMsImV4cCI6MjAxNzI1MDc4M30.z_4PkJu8Z7ZfJHmbjpnz2mJJ4tNFTUK5fYWWXR6Qwvs"
  supabase-service-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlYWVrZ3BhZnB2cnZ5a2V1dmdrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwMTY3NDc4MywiZXhwIjoyMDE3MjUwNzgzfQ.r8X1L4bJvJfB3BqVYfYm6VJeEv8nT5KYVCOhW4RyQ-g"

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # JWT Secret for authentication service (Generated secure 64-byte secrets)
  jwt-secret: "d5ac32b502265184159d1a59e05aa27aceb2dbc36ba86d331132b610fced6738e3b15ee2b2499f961871d014d80313a28a4448141c8e5e1d20b904bea4949729"
  jwt-refresh-secret: "b4f38dea01aa46750a501b8b91aa74af025a7486e6d2675356cd32b023cf8880fb3b988277ef15ceafbfbb1427006779455f2207d00ba9cfe3abf42faf29eed6"

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: sap-microservices
type: Opaque
stringData:
  # Payment Gateway Keys (Generated secure secrets - Replace with actual gateway keys)
  gateway-key: "65797f7c0268f861d570a515092b2199c966492c3f513292a7186fe1b551f4c2"
  webhook-secret: "62d6cc78fd0f692761aebadada85d172050cac5c037a3151"

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: sap-microservices
data:
  # Service URLs for internal communication
  AUTH_SERVICE_URL: "http://auth-service.sap-microservices.svc.cluster.local:3001"
  USER_SERVICE_URL: "http://user-service.sap-microservices.svc.cluster.local:3002"
  CONTENT_SERVICE_URL: "http://content-service.sap-microservices.svc.cluster.local:3005"
  SUBSCRIPTION_SERVICE_URL: "http://subscription-service.sap-microservices.svc.cluster.local:3003"
  
  # Environment settings
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  
  # Feature flags
  ENABLE_ANALYTICS: "true"
  ENABLE_CACHING: "true"
  ENABLE_RATE_LIMITING: "true"
