apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
  namespace: sap-microservices
  labels:
    app: subscription-service
    version: v1
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
        version: v1
        component: backend
    spec:
      containers:
      - name: subscription-service
        image: asia-south1-docker.pkg.dev/sap-project-466005/sap-microservices/subscription-service:latest
        ports:
        - containerPort: 3003
          name: http
        env:
        # Basic service configuration
        - name: PORT
          value: "3003"
        - name: SUBSCRIPTION_SERVICE_PORT
          value: "3003"
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_NAME
          value: "subscription-service"
        
        # Redis for caching (optional but prevents errors)
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: redis-url
        
        # Elasticsearch for search functionality (optional)
        - name: ES_NODE
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: elasticsearch-url
        
        # Supabase configuration (main database)
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-anon-key
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-service-key
        
        # JWT secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        
        # Service URLs for inter-service communication
        - name: USER_SERVICE_PERMISSION_API_URL
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: USER_SERVICE_URL
        
        # Resource limits and requests
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /api/subscription/monitoring/health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/subscription/monitoring/health
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Volume mounts for logs
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      
      # Pod security context
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      
      # Volumes for logs
      volumes:
      - name: logs-volume
        emptyDir: {}
      
      # Node selector for better resource allocation
      nodeSelector:
        kubernetes.io/os: linux

---
apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  namespace: sap-microservices
  labels:
    app: subscription-service
    component: backend
spec:
  selector:
    app: subscription-service
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  type: ClusterIP

---
# HorizontalPodAutoscaler for subscription service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: subscription-service-hpa
  namespace: sap-microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subscription-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
