apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sap-ssd-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
parameters:
  type: ssd
  replication-type: local
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sap-fast-storage
provisioner: rancher.io/local-path
parameters:
  type: nvme
  replication-type: none
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sap-backup-storage
provisioner: rancher.io/local-path
parameters:
  type: hdd
  replication-type: backup
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
