# Grafana Datasources Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app: grafana
    managed-by: module-11-monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true
      jsonData:
        timeInterval: "15s"
        queryTimeout: "60s"
        httpMethod: "POST"
      secureJsonData: {}
      
    - name: Elasticsearch
      type: elasticsearch
      access: proxy
      url: http://sap-backend-logs-es-http:9200
      database: "sap-backend-*"
      editable: true
      jsonData:
        interval: "Daily"
        timeField: "@timestamp"
        esVersion: "8.8.0"
        logMessageField: "message"
        logLevelField: "level"
        maxConcurrentShardRequests: 5
        includeFrozen: false
      secureJsonData: {}
      
    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://sap-backend-tracing-query:16686
      editable: true
      jsonData:
        nodeGraph:
          enabled: true
        traceQuery:
          timeShiftEnabled: true
          spanStartTimeShift: "1h"
          spanEndTimeShift: "1h"
      secureJsonData: {}
      
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      editable: true
      jsonData:
        maxLines: 1000
        derivedFields:
        - datasourceUid: "jaeger"
          matcherRegex: "trace_id=(\\w+)"
          name: "trace_id"
          url: "$${__value.raw}"
      secureJsonData: {}
---
# Grafana Dashboard Provisioning
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
  labels:
    app: grafana
    managed-by: module-11-monitoring
data:
  dashboards.yaml: |
    apiVersion: 1
    
    providers:
    - name: 'SAP Backend Dashboards'
      orgId: 1
      folder: 'SAP Backend'
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 30
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
---
# Grafana Dashboard Files ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-files
  namespace: monitoring
  labels:
    app: grafana
    managed-by: module-11-monitoring
data:
  # This will be populated with dashboard JSON files
  placeholder.json: |
    {
      "dashboard": {
        "title": "Placeholder Dashboard",
        "panels": []
      }
    }
