apiVersion: apps/v1
kind: Deployment
metadata:
  name: sap-backend-production
  namespace: sap-production
  labels:
    app: sap-backend
    env: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sap-backend
      env: production
  template:
    metadata:
      labels:
        app: sap-backend
        env: production
    spec:
      containers:
      - name: sap-backend
        image: ghcr.io/corp-astro/sap-backend:latest
        ports:
        - containerPort: 5001
          name: api-gateway
        - containerPort: 3001
          name: auth-service
        - containerPort: 3002
          name: user-service
        - containerPort: 3003
          name: content-service
        - containerPort: 3004
          name: subscription-service
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: sap-secrets
              key: mongo-uri
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sap-secrets
              key: redis-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: sap-secrets
              key: jwt-secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: sap-secrets
              key: jwt-refresh-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: sap-backend-service
  namespace: sap-production
  labels:
    app: sap-backend
    env: production
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: sap-backend
    env: production

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sap-backend-ingress
  namespace: sap-production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
    - api.corpastro.com
    secretName: sap-backend-tls
  rules:
  - host: api.corpastro.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sap-backend-service
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sap-backend-hpa
  namespace: sap-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sap-backend-production
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
