apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base manifests for all microservices
resources:
  - api-gateway
  - auth-service
  - user-service
  - content-service
  - subscription-service
  - monitoring-service
  - redis-manager
  - email-service
  - security-service

# Common configurations
commonLabels:
  app.kubernetes.io/part-of: sap-backend-system
  app.kubernetes.io/managed-by: argocd

# Apply resource limits and requests to all deployments
patchesStrategicMerge:
  - resource-limits.yaml

# ConfigMap generator for common configurations
configMapGenerator:
  - name: common-config
    literals:
      - LOG_LEVEL=info
      - NODE_ENV=production
      - METRICS_ENABLED=true
      - HEALTH_CHECK_INTERVAL=30s

# Generate image tags from environment variables
images:
  - name: ghcr.io/company/api-gateway
    newTag: latest
  - name: ghcr.io/company/auth-service
    newTag: latest
  - name: ghcr.io/company/user-service
    newTag: latest
  - name: ghcr.io/company/content-service
    newTag: latest
  - name: ghcr.io/company/subscription-service
    newTag: latest
  - name: ghcr.io/company/monitoring-service
    newTag: latest
  - name: ghcr.io/company/redis-manager
    newTag: latest
  - name: ghcr.io/company/email-service
    newTag: latest
  - name: ghcr.io/company/security-service
    newTag: latest
