apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-limits-config
data:
  limits.yaml: |
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        limits:
          cpu: "1000m"
          memory: "1Gi"
        requests:
          cpu: "250m"
          memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-limits-patch
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: NODE_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: LOG_LEVEL
